CREATE DATABASE BDEJEMPLO03
ON PRIMARY(
NAME = N'BDEJEMPLO03_DATA1',
FILENAME = N'C:\LOGS\BDEJEMPLO03_LOG.MDF',
SIZE = 8MB,
MAXSIZE = 80MB,
FILEGROWTH = 10MB
),
FILEGROUP FG_BDEJEMPLO03(
NAME = N'BDEJEMPLO03_DATA2',
FILENAME = N'C:\DATOS\BDEJEMPLO03_DATA2.NDF',
SIZE = 8MB,
MAXSIZE = 10MB,
FILEGROWTH = 10MB
),
(
NAME = N'BDEJEMPLO03_DATA3',
FILENAME = N'C:\DATOS\BDEJEMPLO03_DATA3.NDF',
SIZE = 8MB,
MAXSIZE = 10MB,
FILEGROWTH = 10MB
)
LOG ON(
NAME = N'BDEJEMPLO03_LOG1',
FILENAME = N'C:\LOGS\BDEJEMPLO03_LOG1.LDF',
SIZE = 8MB, 
MAXSIZE = 10MB,
FILEGROWTH = 10MB
),
(NAME = N'BDEJEMPLO03_LOG2',
FILENAME = N'C:\LOGS\BDEJEMPLO03_LOG2.LDF',
SIZE = 8MB,
MAXSIZE = 10MB,
FILEGROWTH = 10MB
)
