CREATE DATABASE BDEJEMPLO01
ON PRIMARY(
NAME = N'BDEJEMPLO01_DATA',
FILENAME = N'C:\DATOS\BDEJEMPLO01.MDF',
SIZE = 8MB,
MAXSIZE = 10MB,
FILEGROWTH = 1MB
)
LOG ON(
NAME = N'BDEJEMPLO01_LOG',
FILENAME = N'C:\LOGS\BDEJEMPLO01_LOG.LDF',
SIZE = 5MB,
MAXSIZE = 10MB,
FILEGROWTH = 10%
)