CREATE DATABASE BDEJEMPLO02
ON PRIMARY(
NAME = N'BDEJEMPLO02_DATA',
FILENAME = N'C:\DATOS\BDEJEMPLO02.MDF',
SIZE = 8MB,
MAXSIZE = 10MB,
FILEGROWTH = 2MB
)
LOG ON(
NAME = N'BDEJEMPLO02_LOG',
FILENAME = N'C:\LOGS\BDEJEMPLO02_LOG.LDF',
SIZE = 8MB,
MAXSIZE = 10MB,
FILEGROWTH = 2MB
)