--PRIMERA PARTE: AUMENTAR SIZE EN 3MB

ALTER DATABASE BDEJEMPLO06
MODIFY FILE(
NAME = N'BDEJEMPLO06FG_DATA',
SIZE = 11MB --ORIGINAL SIZE (8MB)+3MB(INCREMENTO)
)

--SEGUNDA PARTE: REDUCIAR A 5MB
USE BDEJEMPLO06
GO
DBCC SHRINKFILE(N'BDEJEMPLO06FG_DATA', 5)