CREATE DATABASE BDEJEMPLO05
ON PRIMARY(
NAME = N'BDEJEMPLO05_dat',
FILENAME = N'C:\DATOS\BDEJEMPLO_05_data.mdf',
SIZE = 8MB,
MAXSIZE = 20MB,
FILEGROWTH = 30%
)
LOG ON(
NAME = N'BDEJEMPLO05_log',
FILENAME = N'C:\LOGS\BDEJEMPLO_05_log.ldf',
SIZE = 8MB,
MAXSIZE = 20MB,
FILEGROWTH = 10%
)